### ISSUE TITLE
Not working for latest BLTE format

### ISSUE THREAD

**Issue by icyblade** [tomrus88/BLTEExtractor#1]
This BLTEExtractor doesn't work for the latest BLTE format. She raises this error:

> Unhandled Exception: System.IO.InvalidDataException: BLTEHandler: magic
> 
> at BLTEExtractor.BLTEHandler.ExtractData(String path, String name)
> 
> at BLTEExtractor.Program.Main(String[] args)

Can you update the code please?

**Comment by tomrus88** [comment]
There's no plans to update this. Use https://github.com/WoW-Tools/CASCExplorer instead.
